//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLY.XDD.Control.ReadToTxt
{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ribbon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ribbon() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DFHexDemo.Ribbon", typeof(Ribbon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 A 的本地化字符串。
        /// </summary>
        internal static string About_Keytip {
            get {
                return ResourceManager.GetString("About_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;amp;About 的本地化字符串。
        /// </summary>
        internal static string About_LabelTitle {
            get {
                return ResourceManager.GetString("About_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard 的本地化字符串。
        /// </summary>
        internal static string Clipboard_LabelTitle {
            get {
                return ResourceManager.GetString("Clipboard_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C 的本地化字符串。
        /// </summary>
        internal static string Copy_Keytip {
            get {
                return ResourceManager.GetString("Copy_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;amp;Copy 的本地化字符串。
        /// </summary>
        internal static string Copy_LabelTitle {
            get {
                return ResourceManager.GetString("Copy_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the selected bytes and put it to the Clipboard. 的本地化字符串。
        /// </summary>
        internal static string Copy_TooltipDescription {
            get {
                return ResourceManager.GetString("Copy_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy (Ctrl + C) 的本地化字符串。
        /// </summary>
        internal static string Copy_TooltipTitle {
            get {
                return ResourceManager.GetString("Copy_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HC 的本地化字符串。
        /// </summary>
        internal static string CopyHex_Keytip {
            get {
                return ResourceManager.GetString("CopyHex_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Hex 的本地化字符串。
        /// </summary>
        internal static string CopyHex_LabelTitle {
            get {
                return ResourceManager.GetString("CopyHex_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the hex presenation of the selected bytes and put it to the Clipboard. 的本地化字符串。
        /// </summary>
        internal static string CopyHex_TooltipDescription {
            get {
                return ResourceManager.GetString("CopyHex_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Hex (Ctrl + Shift + C) 的本地化字符串。
        /// </summary>
        internal static string CopyHex_TooltipTitle {
            get {
                return ResourceManager.GetString("CopyHex_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X 的本地化字符串。
        /// </summary>
        internal static string Cut_Keytip {
            get {
                return ResourceManager.GetString("Cut_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;amp;Cut 的本地化字符串。
        /// </summary>
        internal static string Cut_LabelTitle {
            get {
                return ResourceManager.GetString("Cut_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut the selected bytes and put it to the Clipboard. 的本地化字符串。
        /// </summary>
        internal static string Cut_TooltipDescription {
            get {
                return ResourceManager.GetString("Cut_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut (Ctrl + X) 的本地化字符串。
        /// </summary>
        internal static string Cut_TooltipTitle {
            get {
                return ResourceManager.GetString("Cut_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editing 的本地化字符串。
        /// </summary>
        internal static string Editing_LabelTitle {
            get {
                return ResourceManager.GetString("Editing_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X 的本地化字符串。
        /// </summary>
        internal static string Exit_Keytip {
            get {
                return ResourceManager.GetString("Exit_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E&amp;amp;xit 的本地化字符串。
        /// </summary>
        internal static string Exit_LabelTitle {
            get {
                return ResourceManager.GetString("Exit_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F 的本地化字符串。
        /// </summary>
        internal static string Find_Keytip {
            get {
                return ResourceManager.GetString("Find_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;amp;Find 的本地化字符串。
        /// </summary>
        internal static string Find_LabelTitle {
            get {
                return ResourceManager.GetString("Find_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find bytes in the file. 的本地化字符串。
        /// </summary>
        internal static string Find_TooltipDescription {
            get {
                return ResourceManager.GetString("Find_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find (Ctrl + F) 的本地化字符串。
        /// </summary>
        internal static string Find_TooltipTitle {
            get {
                return ResourceManager.GetString("Find_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N 的本地化字符串。
        /// </summary>
        internal static string FindNext_Keytip {
            get {
                return ResourceManager.GetString("FindNext_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find &amp;amp;next 的本地化字符串。
        /// </summary>
        internal static string FindNext_LabelTitle {
            get {
                return ResourceManager.GetString("FindNext_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find next bytes in the file. 的本地化字符串。
        /// </summary>
        internal static string FindNext_TooltipDescription {
            get {
                return ResourceManager.GetString("FindNext_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Next (F3) 的本地化字符串。
        /// </summary>
        internal static string FindNext_TooltipTitle {
            get {
                return ResourceManager.GetString("FindNext_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generel 的本地化字符串。
        /// </summary>
        internal static string Generel_LabelTitle {
            get {
                return ResourceManager.GetString("Generel_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 G 的本地化字符串。
        /// </summary>
        internal static string GoTo_Keytip {
            get {
                return ResourceManager.GetString("GoTo_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;amp;Go To 的本地化字符串。
        /// </summary>
        internal static string GoTo_LabelTitle {
            get {
                return ResourceManager.GetString("GoTo_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to the byte position. 的本地化字符串。
        /// </summary>
        internal static string GoTo_TooltipDescription {
            get {
                return ResourceManager.GetString("GoTo_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go To (Ctrl + G) 的本地化字符串。
        /// </summary>
        internal static string GoTo_TooltipTitle {
            get {
                return ResourceManager.GetString("GoTo_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H 的本地化字符串。
        /// </summary>
        internal static string Home_Keytip {
            get {
                return ResourceManager.GetString("Home_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Home_LabelTitle {
            get {
                return ResourceManager.GetString("Home_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 O 的本地化字符串。
        /// </summary>
        internal static string Open_Keytip {
            get {
                return ResourceManager.GetString("Open_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;amp;Open 的本地化字符串。
        /// </summary>
        internal static string Open_LabelTitle {
            get {
                return ResourceManager.GetString("Open_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opens a file. 的本地化字符串。
        /// </summary>
        internal static string Open_TooltipDescription {
            get {
                return ResourceManager.GetString("Open_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open (Ctrl + O) 的本地化字符串。
        /// </summary>
        internal static string Open_TooltipTitle {
            get {
                return ResourceManager.GetString("Open_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T 的本地化字符串。
        /// </summary>
        internal static string Options_Keytip {
            get {
                return ResourceManager.GetString("Options_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Op&amp;amp;tions 的本地化字符串。
        /// </summary>
        internal static string Options_LabelTitle {
            get {
                return ResourceManager.GetString("Options_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V 的本地化字符串。
        /// </summary>
        internal static string Paste_Keytip {
            get {
                return ResourceManager.GetString("Paste_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;amp;Paste 的本地化字符串。
        /// </summary>
        internal static string Paste_LabelTitle {
            get {
                return ResourceManager.GetString("Paste_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste the content of the Clipboard. 的本地化字符串。
        /// </summary>
        internal static string Paste_TooltipDescription {
            get {
                return ResourceManager.GetString("Paste_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste (Ctrl + V) 的本地化字符串。
        /// </summary>
        internal static string Paste_TooltipTitle {
            get {
                return ResourceManager.GetString("Paste_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HV 的本地化字符串。
        /// </summary>
        internal static string PasteHex_Keytip {
            get {
                return ResourceManager.GetString("PasteHex_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Hex 的本地化字符串。
        /// </summary>
        internal static string PasteHex_LabelTitle {
            get {
                return ResourceManager.GetString("PasteHex_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste the hex presentation of the Clipboard. 的本地化字符串。
        /// </summary>
        internal static string PasteHex_TooltipDescription {
            get {
                return ResourceManager.GetString("PasteHex_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Hex (Ctrl + Shift + V) 的本地化字符串。
        /// </summary>
        internal static string PasteHex_TooltipTitle {
            get {
                return ResourceManager.GetString("PasteHex_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Items 的本地化字符串。
        /// </summary>
        internal static string RecentItems_LabelTitle {
            get {
                return ResourceManager.GetString("RecentItems_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S 的本地化字符串。
        /// </summary>
        internal static string Save_Keytip {
            get {
                return ResourceManager.GetString("Save_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;amp;Save 的本地化字符串。
        /// </summary>
        internal static string Save_LabelTitle {
            get {
                return ResourceManager.GetString("Save_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saves the files. 的本地化字符串。
        /// </summary>
        internal static string Save_TooltipDescription {
            get {
                return ResourceManager.GetString("Save_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save (Ctrl + S) 的本地化字符串。
        /// </summary>
        internal static string Save_TooltipTitle {
            get {
                return ResourceManager.GetString("Save_TooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A 的本地化字符串。
        /// </summary>
        internal static string SelectAll_Keytip {
            get {
                return ResourceManager.GetString("SelectAll_Keytip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select &amp;amp;All 的本地化字符串。
        /// </summary>
        internal static string SelectAll_LabelTitle {
            get {
                return ResourceManager.GetString("SelectAll_LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select all bytes of the file. 的本地化字符串。
        /// </summary>
        internal static string SelectAll_TooltipDescription {
            get {
                return ResourceManager.GetString("SelectAll_TooltipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All (Ctrl + A) 的本地化字符串。
        /// </summary>
        internal static string SelectAll_TooltipTitle {
            get {
                return ResourceManager.GetString("SelectAll_TooltipTitle", resourceCulture);
            }
        }
    }
}
