//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLY.XDD.Control {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XLY.XDD.Control.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///		xmlns:local=&quot;clr-namespace:XLY.XDD.Control&quot;&gt;
        ///    &lt;DataTemplate.Resources&gt;
        ///        &lt;local:BoolStringConverter x:Key=&quot;BoolStringConverter&quot; TrueString=&quot;是&quot; FalseString=&quot;否&quot; NullString=&quot;&quot;&gt;&lt;/local:BoolStringConverter&gt;
        ///		&lt;local:GridViewDetailActiveControlIsOpenConverter x:Key=&quot;GridViewDeta [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string BoolTemplate {
            get {
                return ResourceManager.GetString("BoolTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap busy24 {
            get {
                object obj = ResourceManager.GetObject("busy24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///		xmlns:local=&quot;clr-namespace:XLY.XDD.Control&quot;&gt;
        ///    &lt;DataTemplate.Resources&gt;
        ///        &lt;local:DateTimeFormatConverter x:Key=&quot;DateTimeFormatConverter&quot; IsReturnInvalidValue=&quot;False&quot; Format=&quot;#Format#&quot;&gt;&lt;/local:DateTimeFormatConverter&gt;
        ///		&lt;local:GridViewDetailActiveControlIsOpenConverter x:Key [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string DateTimeTemplate {
            get {
                return ResourceManager.GetString("DateTimeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Popup AllowsTransparency=&quot;True&quot; Placement=&quot;Top&quot; VerticalOffset=&quot;3&quot; PlacementTarget=&quot;{Binding ElementName=PART_Root}&quot; 
        ///	   IsOpen=&quot;{Binding Path=IsMouseOver,ElementName=PART_Root, Mode=OneWay}&quot;&gt;
        ///
        ///    &lt;local:GridViewDetailActiveControl&gt;&lt;/local:GridViewDetailActiveControl&gt;
        ///&lt;/Popup&gt; 的本地化字符串。
        /// </summary>
        public static string DetailActionButtonTemplate {
            get {
                return ResourceManager.GetString("DetailActionButtonTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Popup AllowsTransparency=&quot;True&quot; PopupAnimation=&quot;Fade&quot; Placement=&quot;Top&quot; VerticalOffset=&quot;3&quot; PlacementTarget=&quot;{Binding ElementName=PART_Root}&quot; &gt;
        ///    &lt;Popup.IsOpen&gt;
        ///        &lt;MultiBinding Converter=&quot;{StaticResource GridViewDetailActiveControlIsOpenConverter}&quot;&gt;
        ///            &lt;Binding Path=&quot;IsMouseOver&quot; ElementName=&quot;PART_Root&quot; Mode=&quot;OneWay&quot; /&gt;
        ///            &lt;Binding ElementName=&quot;PART_Root&quot; Mode=&quot;OneWay&quot; /&gt;
        ///            &lt;Binding Path=&quot;SelectedItem&quot; Mode=&quot;OneWay&quot; RelativeSource=&quot;{RelativeSource AncestorLevel=1,Mode= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string DetailActionButtonTemplate_For_GridView {
            get {
                return ResourceManager.GetString("DetailActionButtonTemplate_For_GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Popup AllowsTransparency=&quot;True&quot; PopupAnimation=&quot;Fade&quot; Placement=&quot;Top&quot; VerticalOffset=&quot;3&quot; PlacementTarget=&quot;{Binding ElementName=PART_Root}&quot; &gt;
        ///    &lt;Popup.IsOpen&gt;
        ///        &lt;MultiBinding Converter=&quot;{StaticResource GridViewDetailActiveControlIsOpenConverter}&quot;&gt;
        ///            &lt;Binding Path=&quot;IsMouseOver&quot; ElementName=&quot;PART_Root&quot; Mode=&quot;OneWay&quot; /&gt;
        ///            &lt;Binding ElementName=&quot;PART_Root&quot; Mode=&quot;OneWay&quot; /&gt;
        ///            &lt;Binding Path=&quot;SelectedItem&quot; Mode=&quot;OneWay&quot; RelativeSource=&quot;{RelativeSource AncestorLevel=1,Mode= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string DetailActionButtonTemplate_For_TreeView {
            get {
                return ResourceManager.GetString("DetailActionButtonTemplate_For_TreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///		xmlns:local=&quot;clr-namespace:XLY.XDD.Control&quot;&gt;
        ///    &lt;DataTemplate.Resources&gt;
        ///        &lt;local:EnumDescriptionConverter x:Key=&quot;EnumDescriptionConverter&quot;&gt;&lt;/local:EnumDescriptionConverter&gt;
        ///		&lt;local:GridViewDetailActiveControlIsOpenConverter x:Key=&quot;GridViewDetailActiveControlIsOpenConverter [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string EnumTemplate {
            get {
                return ResourceManager.GetString("EnumTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///                    xmlns:local=&quot;clr-namespace:XLY.XDD.Control;assembly=XLY.XDD.Control&quot;&gt;
        ///	&lt;DataTemplate.Resources&gt;
        ///		&lt;local:GridViewDetailActiveControlIsOpenConverter x:Key=&quot;GridViewDetailActiveControlIsOpenConverter&quot;&gt;&lt;/local:GridViewDetailActiveControlIsOpen [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string HighlitColumnTemplate {
            get {
                return ResourceManager.GetString("HighlitColumnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///		xmlns:local=&quot;clr-namespace:XLY.XDD.Control&quot;&gt;
        ///	&lt;DataTemplate.Resources&gt;
        ///		&lt;local:GridViewDetailActiveControlIsOpenConverter x:Key=&quot;GridViewDetailActiveControlIsOpenConverter&quot;&gt;&lt;/local:GridViewDetailActiveControlIsOpenConverter&gt;
        ///    &lt;/DataTemplate.Resources&gt;
        ///    &lt;Grid x:Name=&quot;PART_Ro [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string HyperlinkTemplate {
            get {
                return ResourceManager.GetString("HyperlinkTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///		xmlns:local=&quot;clr-namespace:XLY.XDD.Control&quot;&gt;
        ///    &lt;DataTemplate.Resources&gt;
        ///        &lt;local:StringImageConverter x:Key=&quot;StringImageConverter&quot; IsWhenErrorReturnNull=&quot;True&quot;&gt;&lt;/local:StringImageConverter&gt;
        ///		&lt;local:GridViewDetailActiveControlIsOpenConverter x:Key=&quot;GridViewDetailActiveContr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ImageTemplate {
            get {
                return ResourceManager.GetString("ImageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;IntTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///		xmlns:local=&quot;clr-namespace:XLY.XDD.Control&quot;&gt;
        ///    &lt;IntTemplate.Resources&gt;
        ///        &lt;local:IntDescriptionConverter x:Key=&quot;IntDescriptionConverter&quot;&gt;&lt;/local:IntDescriptionConverter&gt;
        ///		&lt;local:GridViewDetailActiveControlIsOpenConverter x:Key=&quot;GridViewDetailActiveControlIsOpenConverter&quot;&gt;&lt;/l [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string IntTemplate {
            get {
                return ResourceManager.GetString("IntTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap No24 {
            get {
                object obj = ResourceManager.GetObject("No24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///            xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///            xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///			xmlns:local=&quot;clr-namespace:XLY.XDD.Control&quot;&gt;
        ///	&lt;DataTemplate.Resources&gt;
        ///		&lt;local:GridViewDetailActiveControlIsOpenConverter x:Key=&quot;GridViewDetailActiveControlIsOpenConverter&quot;&gt;&lt;/local:GridViewDetailActiveControlIsOpenConverter&gt;
        ///    &lt;/DataTemplate.Resources&gt;
        ///    &lt;Grid x:Name [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string StringTemplate {
            get {
                return ResourceManager.GetString("StringTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap subtract {
            get {
                object obj = ResourceManager.GetObject("subtract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;DataTemplate xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        ///		xmlns:local=&quot;clr-namespace:XLY.XDD.Control&quot;&gt;
        ///        &lt;DataTemplate.Resources&gt;
        ///            &lt;local:ImageThumbnialConverter x:Key=&quot;ImageThumbnialConverter&quot;&gt;&lt;/local:ImageThumbnialConverter&gt;
        ///            &lt;local:StringImageConverter x:Key=&quot;StringImageConverter&quot; IsWhenErrorReturnNull=&quot;True [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ThumbnailImageTemplate {
            get {
                return ResourceManager.GetString("ThumbnailImageTemplate", resourceCulture);
            }
        }
    }
}
